# Generated by Django 4.2 on 2026-06-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('volunteer_stats', 'Volunteer Statistics')], max_length=50)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('skills', models.CharField(choices=[('teaching', 'Teaching'), ('counseling', 'Counseling'), ('mentoring', 'Mentoring'), ('coding', 'Coding'), ('graphic_design', 'Graphic Design'), ('content_writing', 'Content Writing'), ('event_planning', 'Event Planning'), ('fundraising', 'Fundraising'), ('social_media', 'Social Media'), ('other', 'Other')], default='other', max_length=50)),
                ('availability', models.CharField(choices=[('weekdays_morning', 'Weekdays (Morning)'), ('weekdays_evening', 'Weekdays (Evening)'), ('weekends', 'Weekends'), ('flexible', 'Flexible')], default='flexible', max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('hours_contributed', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('registration', 'Registration'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('hours_update', 'Hours Update'), ('status_change', 'Status Change'), ('login', 'Login')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.CharField(blank=True, max_length=100)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='volunteers.volunteer')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
